name: Build Kivy Android APK

on:
  push:
    paths:
      - 'main.py'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq python3-pip build-essential git python3 python3-dev ffmpeg \
                                   libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
                                   libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip install Cython==0.29.19
          pip install kivy

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          buildozer init

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: kivy_app
          path: bin/*.apk
