name: Build Kivy Android APK

on:
  push:
    paths:
      - 'main.py'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget libbz2-dev openjdk-8-jdk

      - name: Setup Java 8
        run: |
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          buildozer init
          echo "android.accept_sdk_license = True" >> buildozer.spec

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: kivy_app
          path: bin/*.apk
